
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 14 18:00:06 MSK 2022
//----------------------------------------------------

package o_project_compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 14;
  public static final int CONST = 5;
  public static final int CHAR = 13;
  public static final int LPAREN = 17;
  public static final int SEMI = 6;
  public static final int CONTINUE = 23;
  public static final int INT = 11;
  public static final int RPAREN = 18;
  public static final int AND = 32;
  public static final int OR = 31;
  public static final int BOOL = 12;
  public static final int COMMA = 9;
  public static final int CLASS = 7;
  public static final int DIV = 29;
  public static final int ASSIGN = 10;
  public static final int IF = 20;
  public static final int THIS = 36;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int RBRACKET = 15;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 30;
  public static final int BREAK = 22;
  public static final int IDENT = 4;
  public static final int VOID = 19;
  public static final int ERROR = 35;
  public static final int LBRACE = 3;
  public static final int ELSE = 33;
  public static final int READ = 25;
  public static final int WHILE = 21;
  public static final int RBRACE = 8;
  public static final int EXTENDS = 16;
  public static final int PRINT = 26;
  public static final int DO = 34;
}

